import * as Helpers from './helpers';
import { generateRandomBunchOfItemListings } from './mock_items';
import { makeRandomFieldGroups } from './mock_fields';
import { allRandomBasicEntities } from './autogenerated_mock_elements';
import { randomPick, getRandomIntInclusive } from './helpers';


export function makeRandomBasicEntityId():string{
    return Helpers.getRandomString(3)+"-entity-"+Helpers.getRandomString(3);
}


export function getBasicEntityById(id:string){
  for(var i=0;i<allRandomBasicEntities.length;i++){
    if(allRandomBasicEntities[i].id === id)
      return allRandomBasicEntities[i];
  }
  return null;
}


export function getRandomBasicEntity(){
  return randomPick(allRandomBasicEntities);
}


export function getRandomBasicEntityFromType(toe: string){
  let possibleResults = [];
  for(var i=0;i<allRandomBasicEntities.length;i++){
    if(allRandomBasicEntities[i].typeOfEntity === toe)
      possibleResults.push(allRandomBasicEntities[i]);
  }
  if(possibleResults) return randomPick(possibleResults);
  return null;
}



let allPossibleThumbnails = [];
for(var i=30;i<150;i++) allPossibleThumbnails.push(`https://placeimg.com/${i}/${i}/any`);

export const getAllEntities = () => allRandomBasicEntities.map(x => getEntity(x.id))

export function getEntity(entityId:string){
  let basicEntity = getBasicEntityById(entityId)
  if(!basicEntity) return null;

  let entities = [];
  const nBubbles = getRandomIntInclusive(30,70)
  for(var i=0;i<nBubbles;i++){
    let eCdta = {
        entity: getRandomBasicEntity(),
        count: getRandomIntInclusive(1000,5000)
    };
    entities.push(eCdta);
  }

  return {
    id: basicEntity.id,
    label: basicEntity.label,
    typeOfEntity: basicEntity.typeOfEntity,
    overviewTab: Helpers.randomPick(allPossibleOverviewTabs),
    fieldsTab: makeRandomFieldGroups(),
    items: generateRandomBunchOfItemListings(allPossibleThumbnails),
    entities,
    extraTab: Helpers.randomPick(allPossibleOverviewTabs),
    wikiTab: {
      text: Helpers.randomPick(allPossibleExtraText),
      url: Helpers.randomPick(allPossibleWikiUrls)
    }
  };
}

const allPossibleWikiUrls = [
  'https://it.wikipedia.org/wiki/Lorem_ipsum',
  'https://en.wikipedia.org/wiki/Alighiero_Boetti',
  'https://it.wikipedia.org/wiki/Milano',
  'https://it.wikipedia.org/wiki/Concetto',
  null
];

const allPossibleExtraText = [
 `Il museo delle belle arti di Nantes fu creato in seguito all'arrêté Chaptal, un decreto 
 consolare del 14 fruttidoro dell'anno IX (1º settembre 1801) che istituiva quattordici 
 musei provinciali in Francia. `,
 `Inizialmente il museo era costituito soprattutto dalla 
 ricca collezione privata raccolta da François Cacault e conservata nel museo-scuola 
 di Clisson.`,
 `Dal 1980 è uno dei cinque principali musei regionali, insieme ai musei di Lione, Bordeaux, Tolosa e Lilla.
 Il museo fu aperto al pubblico nel 1830; la vecchia sede era in rue du Calvaire, nei pressi dell'antico 
 Marché de Feltre`,
 `Dal 1893 il museo è ospitato in rue Clemenceau in un edificio della fine del XIX secolo, dichiarato nel 1975 
 «monumento storico»[4]. Dal 18 dicembre 2011 la sede di rue Clemenceau resterà chiusa per un periodo tempo 
 stimato in 18-24 mesi.`
]


const allPossibleOverviewTabs = [
 `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
  ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
  laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
  voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
  non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
  `Milano e' un comune italiano di 1372810 abitanti, capoluogo della regione Lombardia,
  dell'omonima citta' matropolitana, e centro di una delle piu' popolose aree metropolitane
  d'Europa. Etc...`,
  `Alighiero Boetti (1940-1994) – o Alighiero e Boetti come si firma a partire dal 1971 –
  nasce a Torino dove esordisce nell’ambito dell’Arte Povera nel gennaio del 1967.
  Nel 1972 si trasferisce a Roma, contesto più affine alla sua predilezione per il Sud del mondo.
  Già l’anno precedente ha scoperto l’Afghanistan e avviato il lavoro artistico che affida alle
  ricamatrici afghane, tra cui le Mappe, i planisferi colorati che riproporrà lungo gli anni,
  come registro dei mutamenti politici del mondo.`,
  `Il concetto (o nozione, intesa come cognizione fondamentale) in senso lato è un'idea astratta
  e generale che viene espressa in maniera definita con un procedimento che raccoglie e aggrega
  ("concetto" dal latino concipĕre = cum-capĕre, comprehendĕre) aspetti sensibili particolari che
  una molteplicità di oggetti hanno in comune. Con il concetto la mente è in grado di avere
  chiari i caratteri essenziali e costanti di una specifica realtà. Questi aspetti sostanziali,
  chiamati nella Logica "note definitorie", con il concetto saranno presenti alla mente che sarà
  in grado di riconoscere, senza dover procedere a ulteriori elaborazioni, tutti quegli oggetti
  che presentano il complesso di quelle stesse caratteristiche particolari.`
];