import * as Helpers from './helpers';

import { allRandomBasicItems } from './autogenerated_mock_elements';

import { getAllTypesOfEntity } from './mock_typesOfEntity';

export function autocomplete( args:any ){
  let input = args.input;
  let inputLowerCase = input.toLowerCase();
  if(!input){
    Helpers.throwUserInputErrorParameterNotProvided('input');
  }

  let filtered = allRandomBasicItems.filter(
     (item) => {
       if(item.label.toLowerCase().includes(inputLowerCase)) return true;
       for(var i=0; i<item.info.length;i++){
          if(item.info[i].value.toLowerCase().includes(inputLowerCase)) return true;
       }
       return false;
     }
  );

  const allToE = getAllTypesOfEntity();

  let results = [];
  filtered.forEach( (fe) => {
    results.push({
      item: fe,
      thumbnail: 'https://placeimg.com/50/50/any',
      relatedTOEData: null,
      typeOfEntity: Helpers.randomPick(allToE)
    }
    );
  });

  return results;
}