import * as Helpers from './helpers';

import { allRandomBasicItems } from './autogenerated_mock_elements';

function treeBranch(label:string,withLeaves: boolean){
    this.label=label;
    this.branches=null;
    if(withLeaves) this.leaves = generateRandomBunchOfItemListings();
    else this.leaves=null;
}

const allPossibleLeavesIcons = [
    "n7-icon-archive",
    "n7-icon-atlas",
    "n7-icon-books",
    "n7-icon-camera",
    "n7-icon-earth",
    "n7-icon-file3",
    "n7-icon-illustration"
  ];


function generateRandomBunchOfItemListings(): any[]{
    let itemListings = [];
    let numOfItems = Helpers.getRandomIntInclusive(10,30);
    let basicItemsIdx = Helpers.pickNDistinctPositiveIntegers(allRandomBasicItems.length-1,numOfItems);
    basicItemsIdx.forEach(bIdx => {
        let itemL = {
            item:allRandomBasicItems[bIdx],
            thumbnail: Helpers.randomPick(allPossibleLeavesIcons),
            relatedTOEData: null
        };
        itemListings.push(itemL); 
    });
    return itemListings;
}



export function getTreeOfItems(treeId:String){
    let centroArchiviBranches = [];

    [ '5+1AA Agenzia di Architettura', 'ABDR Architetti Associati', 'AWP', 
    'BOERI Cini', 'Campo BAEZA Alberto', 'CASSANI Matilde', 'Guerri Danilo',
    'ISOLA Aimaro' ].forEach( (lbl) => centroArchiviBranches.push( new treeBranch(lbl,true) ) ) 
    let nerviPierLuigi = new treeBranch('NERVI Pier Luigi',false);
    nerviPierLuigi.branches = [];
    [ 'Attività Professionale', 'Materiali fotografici e audio-video', 'Corrispondenza', 'Ricerca e didattica',
     'Materiali e stampa', 'Documenti d\'impresa', 'Biblioteca aggregta' 
    ].forEach( (lbl) => nerviPierLuigi.branches.push( new treeBranch(lbl,true) ) );
    centroArchiviBranches.push( nerviPierLuigi );  
    [ 'OBR Open Building Research', 'PANICONI Mario - PEDICONI Giulio', 'PERUGINI Giuseppe',
    'PETRESCHI Marco', 'PIANO Renzo', 'PIERLUISI Franco', 'RIVA Umberto', 'ROTA Italo',
    'SIZA Alvaro', 'SUPERSTUDIO' ].forEach( (lbl) => centroArchiviBranches.push( new treeBranch(lbl,true) ) )   

    if(treeId==='patrimonioId')
        return {
            label: "Albero di navigazione",
            leaves: null,
            branches: [
                {
                    label: "Collezione D'arte",
                    leaves: null,
                    branches: [
                        {
                            label: "Collezione Arte",
                            branches: null,
                            leaves: generateRandomBunchOfItemListings()
                        }
                    ]
                },
                {
                    label: "Centro Archivi",
                    leaves: null,
                    branches: centroArchiviBranches
                }
            ]
        }

    return null;
}

