import * as Helpers from './helpers';

import { allRandomBasicItems, allRandomItemDetails } from './autogenerated_mock_elements';

function getBasicItemById(id:String):any{
  for(var i=0;i<allRandomBasicItems.length;i++){
    if(allRandomBasicItems[i].id===id){
      return allRandomBasicItems[i];
    }
  }
  return null;
}


export function getAllBasicItems(){
  return allRandomBasicItems;
}


export function getItemDetails(itemId: String){
  let itemDetails = allRandomItemDetails[itemId+''];
  return ( itemDetails ? itemDetails : null );
}