
  import * as Helpers from '../helpers';


  const allPossibleRandomItemLabels = [
    "Green squares C",
    "As Nights fall over...",
    "Pisa, la torre pendente",
    "Randomness madness",
    "Untitled Item",
    "Placeholder Item",
    "This is a Test",
    "Random Element",
    "Generic Label/Title"
  ];
  
  const allPossibleRandomItemAuthors = [
    "Giulio Andreini",
    "Romeo Zitarosa",
    "Dario Piotrowicz",
    "Edgar Gomez",
    "Duccio Duccio",
    "Chiara Aiola",
    "Anonymous",
    "Generic Author"
  ];
  
  
  const allPossibleRandomItemIcons = [
    "n7-icon-action-alt",
    "n7-icon-archive",
    "n7-icon-atlas",
    "n7-icon-biography-alt",
    "n7-icon-books",
    "n7-icon-calendar-alt",
    "n7-icon-camera",
    "n7-icon-clipboard-check",
    "n7-icon-compass",
    "n7-icon-earth",
    "n7-icon-file3",
    "n7-icon-illustration",
    "n7-icon-lightbulb"
  ];
  
  
  
  const allPossibleRandomItemTexts = [
    '<html>A short text for a random item!</html>',
    '<html>This is a text for an item! maybe the filed should be called "html" instead of "text"</html>',
    '<html>A text/description for a very interesting item <br> The item also presents some interesting <b>styling</b> and even spreads across <br> multiple <br> lines </html>',
  ];
  
  
  function makeRandomItemId():String{
    return Helpers.getRandomString(3)+"-item-"+Helpers.getRandomString(3);
  }

  function makeRandomFieldGroupId():String{
    return Helpers.getRandomString(3)+"-fieldGroup-"+Helpers.getRandomString(3);
  }

  function makeRandomFieldId():String{
    return Helpers.getRandomString(3)+"-field-"+Helpers.getRandomString(3);
  }


  function makeRandomFieldGroups():any{
    let nOfGroups = Helpers.getRandomIntInclusive(0,5);
    if(nOfGroups==0) return null;

    let groups = [];
    for(var i=0;i<nOfGroups;i++){
      let group = {};
      group['id']=makeRandomFieldGroupId();
      group['label']=Helpers.randomPick(['Gruppo A','Gruppo 1']);// add random pick
      group['fields']=[];
      let nOfFields = Helpers.getRandomIntInclusive(1,5);
      for(var j=0;j<nOfFields;j++){
        let field = {};
        field['id']=makeRandomFieldId();
        field['key']='testKey';// add random pick
        field['value']='testValue';// add random pick
        group['fields'].push(field);
      }
      groups.push(group);
    }
    return groups;
  }

  
  const numOfAllItems = 500;
  
  
  const allRandomBasicItems = [];
  const allRandomItemDetails = {};
  
  for(var i=0;i<numOfAllItems;i++){
    let basicItem = {
      id: makeRandomItemId(),
      label: Helpers.randomPick(allPossibleRandomItemLabels),
      author: Helpers.randomPick(allPossibleRandomItemAuthors),
      icon: Helpers.randomPick(allPossibleRandomItemIcons)
    };
    allRandomBasicItems.push(basicItem);
  
    var width = Helpers.getRandomIntInclusive(900,1800);
    var height = Helpers.getRandomIntInclusive(500,800);
  
    allRandomItemDetails[basicItem.id+''] = {
      item: basicItem,
      title: basicItem.label,
      image: `https://placeimg.com/${width}/${height}/any`,
      text: Helpers.randomPick(allPossibleRandomItemTexts),
      fields: makeRandomFieldGroups(),
      connectedEntities: null, // add random pick
      similarItems: null // add random pick
    };
  
  }
  









const fs = require('fs')
fs.writeFileSync('./mocks/autogenerated_mock_elements.ts',
`///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
////////////  AUTOGENERATED FILE WITH DIFFERENT MOCK ELEMENTS /////////////
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

export const allRandomBasicItems = ${JSON.stringify(allRandomBasicItems)};


export const allRandomItemDetails = ${JSON.stringify(allRandomItemDetails)};`);


console.log('mock_elements.ts file generated');